### ISSUE TITLE
[BUG] reactive-extensions

### ISSUE THREAD

**Issue by Arhell** [reactiveui/website#672] opened 2021-10-14 02:05 UTC
Problem on these pages, links are not generated correctly
example https://www.reactiveui.net/reactive-extensions/accept/notification(t).accept

See Also => Notification<T> Class

Namespace => System.Reactive

on all pages this

**Comment by glennawatson** [comment] 2021-10-14 02:07
This is a duplicate of https://github.com/reactiveui/website/issues/441

**Closed by glennawatson** 2021-10-14 02:07 UTC
